In [598]:
import torch 
import torch.nn as nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_sequence

In [599]:
class LstmClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, bidirectional = True):
        super().__init__()

        self.input_sz = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers,bidirectional=bidirectional, dropout=0.2)
        self.clf = nn.Sequential(
            nn.Linear(2 * hidden_size, 4 * hidden_size),
            nn.LayerNorm(4 * hidden_size),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(4 * hidden_size, 7)
        )

    def forward(self, x, lengths):
        B, T, F = x.shape
        packed_x = pack_padded_sequence(x, lengths=lengths.cpu(), batch_first=True, enforce_sorted=False)

        output, (h, c) = self.lstm(packed_x) # output -> T, B, 2*H, h -> B, 2*H, c -> B, 2*H
        clf_tensor = torch.cat([h[-2], h[-1]], dim=-1)
        logits = self.clf(clf_tensor)

        return logits

In [600]:
import pandas as pd

In [601]:
df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

In [602]:
df = df_test.groupby('IDSample')

In [603]:
subtask1 = []

In [604]:
for id, gr in df:
    subtask1.append(gr['FrameNumber'].max())

In [605]:
df_train.head()

,IDSample,FrameNumber,J1X,J1Y,J1Z,J2X,J2Y,J2Z,J3X,J3Y,...,J23Y,J23Z,J24X,J24Y,J24Z,J25X,J25Y,J25Z,Action,Camera
0,1,1,0.164490,0.291355,3.091319,0.189296,0.615010,3.080443,0.209298,0.928650,...,0.249604,2.929706,0.237679,0.185178,2.881282,0.290780,0.236038,2.852048,3,1
1,1,2,0.164051,0.291135,3.091265,0.187257,0.614560,3.080929,0.206220,0.927991,...,0.242949,2.934857,0.237713,0.184868,2.881657,0.288819,0.236270,2.851250,3,1
2,1,3,0.160394,0.291922,3.091712,0.183053,0.614688,3.081785,0.202935,0.927368,...,0.261962,2.940350,0.237603,0.182165,2.880324,0.286495,0.221468,2.868750,3,1
3,1,4,0.157784,0.291979,3.090791,0.179416,0.614119,3.081133,0.198786,0.925982,...,0.257649,2.934111,0.231934,0.184934,2.879659,0.289556,0.229324,2.863987,3,1
4,1,5,0.154023,0.289773,3.091381,0.174946,0.611712,3.081385,0.194107,0.923457,...,0.252397,2.932880,0.223781,0.178191,2.879539,0.278711,0.216850,2.864786,3,1

In [606]:
y_train = df_train[['IDSample','Action', 'Camera']]

In [607]:
X_train = df_train.drop(columns = ['Action', 'Camera'])
X_test = df_test

In [608]:
X_test.head()

,IDSample,FrameNumber,J1X,J1Y,J1Z,J2X,J2Y,J2Z,J3X,J3Y,...,J22Z,J23X,J23Y,J23Z,J24X,J24Y,J24Z,J25X,J25Y,J25Z
0,3361,1,-0.707474,-0.558262,3.659323,-0.712082,-0.224231,3.667649,-0.713740,0.105216,...,3.545863,-0.794203,-0.362780,3.570667,-0.579403,-0.309495,3.535433,-0.504720,-0.324692,3.571167
1,3361,2,-0.701481,-0.555497,3.653012,-0.708182,-0.223555,3.663723,-0.711626,0.104554,...,3.548151,-0.811219,-0.366514,3.571125,-0.578761,-0.305720,3.534078,-0.510337,-0.321618,3.561222
2,3361,3,-0.699060,-0.555092,3.648376,-0.703081,-0.221451,3.657866,-0.703695,0.108269,...,3.541340,-0.804400,-0.374341,3.560300,-0.580567,-0.325120,3.524870,-0.513830,-0.323958,3.553727
3,3361,4,-0.692364,-0.554330,3.643446,-0.697653,-0.221149,3.653842,-0.699972,0.107870,...,3.529219,-0.813160,-0.380458,3.553818,-0.577347,-0.340454,3.514266,-0.514556,-0.339562,3.545001
4,3361,5,-0.690229,-0.554802,3.639278,-0.693909,-0.220811,3.649389,-0.694498,0.108867,...,3.524888,-0.801957,-0.374812,3.546375,-0.574917,-0.336967,3.497991,-0.505000,-0.345860,3.545715

In [609]:
ids = X_test.IDSample.unique()

In [610]:
import numpy as np

In [611]:
sequences_train = df_train.groupby(by='IDSample')
sequences_test = X_test.groupby(by='IDSample')

In [612]:
for id, gr in sequences_train:
    print(np.array(gr.drop(columns=['FrameNumber', 'IDSample'])).mean(axis = 0))
    break

[ 0.11652088  0.32643804  3.03202005  0.13438514  0.64838321  3.02755837
  0.15099264  0.95976793  3.01048254  0.11354451  1.09134258  3.03140586
  0.02486561  0.84653266  3.11254686  0.00965282  0.58110601  3.02568225
 -0.03324416  0.3457645   2.97468496 -0.01988331  0.31032946  2.96313118
  0.22827787  0.79913363  2.88459919  0.29816289  0.53658051  2.8254846
  0.25397983  0.32283666  2.79316716  0.22635254  0.2849953   2.79462632
  0.06827117  0.30486552  3.0611524   0.13222708 -0.06681493  3.11160905
  0.20009956 -0.43023999  3.21457826  0.15940487 -0.50072864  3.12614089
  0.16167286  0.33943529  2.9226943  -0.02838612  0.05830812  2.80806886
  0.10096582 -0.25732273  2.97147802  0.04651932 -0.33409661  2.90295511
  0.14703849  0.88345183  3.01708289 -0.02923771  0.26458732  2.93917902
 -0.01200594  0.31517549  2.93113482  0.20234824  0.22494186  2.80016549
  0.26296331  0.27259341  2.78972214  3.          1.        ]

In [613]:
from torch.utils.data import Dataset, DataLoader, random_split

In [614]:
class lstmdata(Dataset):
    def __init__(self, sequences, label = False):
        super().__init__()

        self.seq = []
        self.labels = [] if label else None 

        if label is not False:
            for id, gr in sequences:
                    array = np.array(gr.drop(columns=['FrameNumber', 'IDSample', 'Action', 'Camera']))
                    T = array.shape[0]

                    mean = np.repeat(array.mean(axis=0, keepdims=True), T, axis=0)
                    max_ = np.repeat(array.max(axis=0, keepdims=True), T, axis=0)
                    min_ = np.repeat(array.min(axis=0, keepdims=True), T, axis=0)
                    std = np.repeat(array.std(axis=0, keepdims=True), T, axis=0)

                    array = np.concatenate(
                        [array, mean, max_, min_, std],
                        axis=1
                    )

                    self.seq.append(
                        torch.tensor(array, dtype=torch.float32)
                    )
                    grup = gr.drop(columns=['FrameNumber', 'IDSample'])
                    self.labels.append([grup['Action'].iloc[0], grup['Camera'].iloc[0]])
        else:
            for id, gr in sequences:
                array = np.array(gr.drop(columns=['FrameNumber', 'IDSample']))

                T = array.shape[0]

                mean = np.repeat(array.mean(axis=0, keepdims=True), T, axis=0)
                max_ = np.repeat(array.max(axis=0, keepdims=True), T, axis=0)
                min_ = np.repeat(array.min(axis=0, keepdims=True), T, axis=0)
                std = np.repeat(array.std(axis=0, keepdims=True), T, axis=0)

                array = np.concatenate(
                    [array, mean, max_, min_, std],
                    axis=1
                )

                self.seq.append(
                    torch.tensor(array, dtype=torch.float32)
                )
                
    def __len__(self):
        return len(self.seq)

    def __getitem__(self, index):

        seq = self.seq[index]

        if self.labels is not None:
            return seq, self.labels[index][0], self.labels[index][1]
        return seq

In [615]:
len(y_train)

313762

In [616]:
train_data = lstmdata(sequences_train, True)
test_data = lstmdata(sequences_test)

In [617]:
len(train_data[0][0])

57

In [618]:
train_data, valid_data = random_split(train_data,[int(len(train_data)*0.8), len(train_data) - int(len(train_data)*0.8)])

In [619]:
def collate_fn(batch):
    seq, actions, cameras = zip(*batch)
    
    lengths = torch.tensor([len(s) for s in seq])

    padded_seq = pad_sequence(
        seq,
        batch_first=True,
        padding_value=0
    )

    return padded_seq, lengths, torch.tensor(actions), torch.tensor(cameras)

In [620]:
def collate_fn1(batch):
    seq = batch
    
    lengths = torch.tensor([len(s) for s in seq])

    padded_seq = pad_sequence(
        seq,
        batch_first=True,
        padding_value=0
    )

    return padded_seq, lengths

In [621]:
train_dataloader = DataLoader(train_data, batch_size=64, shuffle=True, collate_fn = collate_fn, drop_last=True)
valid_dataloader = DataLoader(valid_data, batch_size=64, collate_fn = collate_fn, shuffle=False)
test_dataloader = DataLoader(test_data, batch_size=64, collate_fn = collate_fn1, shuffle=False)

In [622]:
next(iter(train_dataloader))

(tensor([[[ 0.0466,  0.0911,  3.4064,  ...,  0.1779,  0.1738,  0.1415],
          [ 0.0459,  0.0913,  3.4068,  ...,  0.1779,  0.1738,  0.1415],
          [ 0.0457,  0.0903,  3.4072,  ...,  0.1779,  0.1738,  0.1415],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[-0.4671, -0.3683,  2.5649,  ...,  0.2049,  0.2785,  0.0610],
          [-0.4709, -0.3688,  2.5738,  ...,  0.2049,  0.2785,  0.0610],
          [-0.4712, -0.3686,  2.5735,  ...,  0.2049,  0.2785,  0.0610],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[ 0.2487, -0.0155,  3.6434,  ...,  0.0265,  0.0684,  0.0293],
          [ 0.2500, -0.0127,  3.6416,  ...,  0.0265,  0.0684,  0.0293],
          [ 0.2502, -0.0102,  3.6402,  ...,  0.0265,  0.0684,  0.0293],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         ...,

         [[-0.3001, -0.0262,  3.7401,  ...,  0.0056,  0.0059,  0.0099],
          [-0.3085, -0.0176,  3.7470,  ...,  0.0056,  0.0059,  0.0099],
          [-0.3022, -0.0191,  3.7472,  ...,  0.0056,  0.0059,  0.0099],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[ 0.5551, -0.2901,  3.3613,  ...,  0.1372,  0.3255,  0.1847],
          [ 0.5575, -0.2994,  3.3541,  ...,  0.1372,  0.3255,  0.1847],
          [ 0.5600, -0.2976,  3.3600,  ...,  0.1372,  0.3255,  0.1847],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[-0.3849, -0.6130,  2.7262,  ...,  0.1246,  0.2128,  0.1080],
          [-0.3827, -0.6126,  2.7272,  ...,  0.1246,  0.2128,  0.1080],
          [-0.3823, -0.6127,  2.7272,  ...,  0.1246,  0.2128,  0.1080],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]]),
 tensor([142,  67,  48, 102,  67,  61, 156,  48,  48,  94, 195,  64,  77,  53,
         153,  59, 135, 169,  83, 176, 100,  48,  67,  93,  58, 129, 157, 124,
         138, 215,  59,  95, 135,  47, 128,  70,  74,  56,  51,  69, 161, 134,
          45, 194,  83,  86, 159,  66,  84,  56, 166,  64,  63,  65,  48,  57,
          42,  54,  49,  60,  85,  63,  58,  57]),
 tensor([2, 4, 1, 3, 0, 4, 2, 1, 4, 3, 2, 4, 3, 1, 2, 1, 2, 2, 1, 2, 3, 4, 0, 0,
         0, 2, 2, 3, 2, 2, 1, 3, 2, 4, 2, 1, 4, 4, 1, 1, 2, 1, 4, 2, 0, 3, 2, 4,
         4, 4, 2, 0, 1, 3, 0, 0, 4, 4, 4, 1, 1, 0, 4, 0]),
 tensor([2, 1, 2, 2, 1, 2, 2, 3, 1, 1, 2, 1, 1, 2, 2, 3, 1, 3, 2, 1, 3, 2, 3, 1,
         2, 1, 2, 3, 2, 2, 2, 1, 2, 1, 2, 2, 2, 3, 1, 3, 3, 2, 2, 2, 2, 1, 1, 3,
         3, 2, 2, 1, 3, 2, 1, 3, 2, 2, 3, 3, 1, 3, 3, 3]))

In [623]:
epochs = 35
model = LstmClassifier(375, 128, 2, True)
optimizer = torch.optim.AdamW(model.parameters(),lr = 1e-3, weight_decay = 1e-4)
loss_action = torch.nn.CrossEntropyLoss()
loss_camera = torch.nn.CrossEntropyLoss()

In [624]:
from tqdm import tqdm
device = "mps" if torch.mps.is_available() else "cpu"
model = model.to(device)

In [625]:
torch.arange(5)[4]

tensor(4)

In [626]:
from sklearn.metrics import accuracy_score as accuracy

In [627]:
for epoch in range(epochs):
    train_losses = []
    valid_losses = []


    model.train()
    train_bar = tqdm(train_dataloader, desc = "Training..")
    total_train_loss = 0.
    train_preds = []
    valid_preds = []

    train_true = []
    valid_true = []

    for X, lengths, actions, cameras in train_bar:

        optimizer.zero_grad()
        X, lengths, actions, cameras = X.to(device), lengths.to(device), actions.to(device), cameras.to(device)

        y_hat = model(X,lengths)
        loss_a = loss_action(y_hat[:, :4], actions)
        loss_c = loss_camera(y_hat[:, 4:], cameras)

        train_preds.append(torch.argmax(y_hat[:,:4], dim = 1))
        train_true.append(actions)

        loss = loss_a + loss_c
        total_train_loss+=loss.item()
        train_losses.append(loss.item())

        train_bar.set_postfix(loss = loss.item())
        loss.backward()
        optimizer.step()
    avg_train_loss = total_train_loss / len(train_dataloader)
    train_preds = torch.cat(train_preds)
    train_true = torch.cat(train_true)
    print(f"training epoch {epoch} has avg loss {avg_train_loss}")
    print(f"training accuracy on epoch {epoch} is {accuracy(train_true.detach().cpu().numpy(), train_preds.detach().cpu().numpy())}")


    model.eval()
    valid_bar = tqdm(valid_dataloader, desc = "Validating..")
    total_valid_loss = 0.
    with torch.inference_mode():
        for X, lengths, actions, cameras in valid_bar:
        
                X, lengths, actions, cameras = X.to(device), lengths.to(device), actions.to(device), cameras.to(device)
        
                y_hat = model(X,lengths)
                loss_a = loss_action(y_hat[:, :4], actions)
                loss_c = loss_camera(y_hat[:, 4:], cameras)

                valid_preds.append(torch.argmax(y_hat[:,:4], dim = 1))
                valid_true.append(actions)
        
                loss = loss_a + loss_c
                total_valid_loss+=loss.item()
                valid_losses.append(loss.item())
        
                valid_bar.set_postfix(loss = loss.item())
    avg_valid_loss = total_valid_loss / len(valid_dataloader)
    valid_preds = torch.cat(valid_preds)
    valid_true = torch.cat(valid_true)
    print(f"validating epoch {epoch} has avg loss {avg_valid_loss}")
    print(f"validation accuracy on epoch {epoch} is {accuracy(valid_true.detach().cpu().numpy(), valid_preds.detach().cpu().numpy())}")

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.55it/s, loss=1.27]

training epoch 0 has avg loss 1.5555332201283152
training accuracy on epoch 0 is 0.2629573170731707

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.24it/s, loss=1.31]

validating epoch 0 has avg loss 1.194651560349898
validation accuracy on epoch 0 is 0.4008941877794337

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.79it/s, loss=1.05]

training epoch 1 has avg loss 1.1308374448520382
training accuracy on epoch 1 is 0.4603658536585366

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.48it/s, loss=0.994]

validating epoch 1 has avg loss 0.9552170851013877
validation accuracy on epoch 1 is 0.5245901639344263

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.78it/s, loss=0.809]

training epoch 2 has avg loss 0.9914456009864807
training accuracy on epoch 2 is 0.5270579268292683

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.49it/s, loss=1.06]

validating epoch 2 has avg loss 0.9514302286234769
validation accuracy on epoch 2 is 0.5320417287630402

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.80it/s, loss=0.699]

training epoch 3 has avg loss 0.816298080653679
training accuracy on epoch 3 is 0.6234756097560976

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.29it/s, loss=0.81]

validating epoch 3 has avg loss 0.7448684898289767
validation accuracy on epoch 3 is 0.5588673621460507

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.77it/s, loss=0.721]

training epoch 4 has avg loss 0.7890902088909615
training accuracy on epoch 4 is 0.6432926829268293

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.30it/s, loss=0.572]

validating epoch 4 has avg loss 0.5876986276019703
validation accuracy on epoch 4 is 0.7317436661698957

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.78it/s, loss=0.667]

training epoch 5 has avg loss 0.6026458987375585
training accuracy on epoch 5 is 0.7374237804878049

Validating..: 100%|██████████| 11/11 [00:01<00:00, 10.30it/s, loss=0.494]

validating epoch 5 has avg loss 0.5600497722625732
validation accuracy on epoch 5 is 0.7198211624441133

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.78it/s, loss=0.565]

training epoch 6 has avg loss 0.6817701880524798
training accuracy on epoch 6 is 0.7008384146341463

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.97it/s, loss=0.531]

validating epoch 6 has avg loss 0.5558031634850935
validation accuracy on epoch 6 is 0.7228017883755589

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.72it/s, loss=0.684]

training epoch 7 has avg loss 0.5990123894156479
training accuracy on epoch 7 is 0.7423780487804879

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.96it/s, loss=0.775]

validating epoch 7 has avg loss 0.6708103851838545
validation accuracy on epoch 7 is 0.6512667660208644

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.74it/s, loss=0.737]

training epoch 8 has avg loss 0.6007772785861317
training accuracy on epoch 8 is 0.7317073170731707

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.92it/s, loss=0.758]

validating epoch 8 has avg loss 0.6417166834527795
validation accuracy on epoch 8 is 0.7049180327868853

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.76it/s, loss=0.418]

training epoch 9 has avg loss 0.5425595539372142
training accuracy on epoch 9 is 0.75

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.45it/s, loss=0.454]

validating epoch 9 has avg loss 0.4910835488276048
validation accuracy on epoch 9 is 0.7466467958271237

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.54it/s, loss=0.522]

training epoch 10 has avg loss 0.5124994094778852
training accuracy on epoch 10 is 0.7652439024390244

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.76it/s, loss=0.735]

validating epoch 10 has avg loss 0.6202211813493208
validation accuracy on epoch 10 is 0.7049180327868853

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.78it/s, loss=0.551]

training epoch 11 has avg loss 0.5378060522602826
training accuracy on epoch 11 is 0.7576219512195121

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.74it/s, loss=0.573]

validating epoch 11 has avg loss 0.5554760071364316
validation accuracy on epoch 11 is 0.7317436661698957

Training..: 100%|██████████| 41/41 [00:14<00:00,  2.76it/s, loss=0.471]

training epoch 12 has avg loss 0.5207333390305682
training accuracy on epoch 12 is 0.7641006097560976

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.67it/s, loss=0.406]

validating epoch 12 has avg loss 0.4839323569427837
validation accuracy on epoch 12 is 0.7436661698956781

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.73it/s, loss=0.482]

training epoch 13 has avg loss 0.4893816193429435
training accuracy on epoch 13 is 0.7663871951219512

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.32it/s, loss=0.525]

validating epoch 13 has avg loss 0.5166816196658395
validation accuracy on epoch 13 is 0.7421758569299552

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.72it/s, loss=0.585]

training epoch 14 has avg loss 0.498852633121537
training accuracy on epoch 14 is 0.7660060975609756

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.70it/s, loss=0.531]

validating epoch 14 has avg loss 0.5906664214350961
validation accuracy on epoch 14 is 0.7183308494783904

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.64it/s, loss=0.702]

training epoch 15 has avg loss 0.5359814181560423
training accuracy on epoch 15 is 0.7560975609756098

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.38it/s, loss=0.499]

validating epoch 15 has avg loss 0.5107638158581473
validation accuracy on epoch 15 is 0.7406855439642325

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.64it/s, loss=0.569]

training epoch 16 has avg loss 0.4899202287197113
training accuracy on epoch 16 is 0.7686737804878049

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.44it/s, loss=0.422]

validating epoch 16 has avg loss 0.4940367774529891
validation accuracy on epoch 16 is 0.7302533532041728

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.62it/s, loss=0.381]

training epoch 17 has avg loss 0.48326100663440985
training accuracy on epoch 17 is 0.7652439024390244

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.25it/s, loss=0.42]

validating epoch 17 has avg loss 0.4507741928100586
validation accuracy on epoch 17 is 0.7511177347242921

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.54it/s, loss=0.435]

training epoch 18 has avg loss 0.45999416418191863
training accuracy on epoch 18 is 0.7690548780487805

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.36it/s, loss=0.435]

validating epoch 18 has avg loss 0.4603393457152627
validation accuracy on epoch 18 is 0.7496274217585693

Training..: 100%|██████████| 41/41 [00:15<00:00,  2.57it/s, loss=0.448]

training epoch 19 has avg loss 0.4564558703724931
training accuracy on epoch 19 is 0.7732469512195121

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.43it/s, loss=0.373]

validating epoch 19 has avg loss 0.47035657546736975
validation accuracy on epoch 19 is 0.7436661698956781

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.56it/s, loss=0.388]

training epoch 20 has avg loss 0.4498500191583866
training accuracy on epoch 20 is 0.7751524390243902

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.37it/s, loss=0.377]

validating epoch 20 has avg loss 0.44775349172678863
validation accuracy on epoch 20 is 0.7436661698956781

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.52it/s, loss=0.315]

training epoch 21 has avg loss 0.4413767849526754
training accuracy on epoch 21 is 0.7713414634146342

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.36it/s, loss=0.408]

validating epoch 21 has avg loss 0.4421354992823167
validation accuracy on epoch 21 is 0.7466467958271237

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.52it/s, loss=0.452]

training epoch 22 has avg loss 0.4378893208212969
training accuracy on epoch 22 is 0.7789634146341463

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.39it/s, loss=0.567]

validating epoch 22 has avg loss 0.5622567128051411
validation accuracy on epoch 22 is 0.7034277198211625

Training..: 100%|██████████| 41/41 [00:16<00:00,  2.54it/s, loss=0.61]

training epoch 23 has avg loss 0.49606669457947333
training accuracy on epoch 23 is 0.7614329268292683

Validating..: 100%|██████████| 11/11 [00:01<00:00,  9.28it/s, loss=0.639]

validating epoch 23 has avg loss 0.5978595560247247
validation accuracy on epoch 23 is 0.7004470938897168

Training..:  32%|███▏      | 13/41 [00:05<00:12,  2.28it/s, loss=0.577]

KeyboardInterrupt:

In [ ]:
next(iter(test_dataloader))

(tensor([[[-0.7075, -0.5583,  3.6593,  ...,  3.7765, -1.0362,  1.9723],
          [-0.7015, -0.5555,  3.6530,  ...,  3.7742, -0.9980,  1.9688],
          [-0.6991, -0.5551,  3.6484,  ...,  3.7629, -1.0012,  1.9617],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[-0.1298, -0.4527,  2.7718,  ...,  2.8853, -1.0341,  1.4052],
          [-0.1298, -0.4531,  2.7720,  ...,  2.8856, -1.0480,  1.4024],
          [-0.1300, -0.4531,  2.7720,  ...,  2.8858, -1.0352,  1.4052],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[ 0.1541,  0.2641,  3.5932,  ...,  3.7937, -0.5460,  1.6064],
          [ 0.1376,  0.2605,  3.6078,  ...,  3.8040, -0.6079,  1.6189],
          [ 0.1432,  0.2585,  3.6042,  ...,  3.8047, -0.5440,  1.6165],
          ...,
          [ 0.1330,  0.3191,  3.6532,  ...,  4.0030, -0.5680,  1.6234],
          [ 0.1340,  0.3162,  3.6524,  ...,  4.0025, -0.5630,  1.6207],
          [ 0.1339,  0.3140,  3.6544,  ...,  4.0020, -0.5652,  1.6213]],

         ...,

         [[ 0.2422,  0.3016,  3.3486,  ...,  3.5668, -0.5098,  1.4715],
          [ 0.2419,  0.3014,  3.3487,  ...,  3.5689, -0.5099,  1.4717],
          [ 0.2411,  0.3013,  3.3488,  ...,  3.5695, -0.5302,  1.4745],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[-0.5297, -0.3376,  3.1300,  ...,  3.3902, -0.8133,  1.5863],
          [-0.5307, -0.3377,  3.1301,  ...,  3.3888, -0.8136,  1.5866],
          [-0.5301, -0.3378,  3.1301,  ...,  3.3877, -0.8117,  1.5862],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[-0.4119, -0.0445,  3.5389,  ...,  3.7058, -0.7349,  1.7757],
          [-0.4137, -0.0450,  3.5432,  ...,  3.7033, -0.7372,  1.7817],
          [-0.4111, -0.0684,  3.5621,  ...,  3.7111, -0.7481,  1.7893],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]]),
 tensor([124,  78, 207,  66,  83,  65,  86, 100,  87,  90, 161,  86,  71, 200,
          78, 139, 116,  51,  91, 139,  75,  71,  88,  66, 115,  79,  66,  68,
          81,  67, 181,  71,  95,  67, 158,  71, 132,  81, 110,  65,  79, 138,
         123,  74, 107,  59,  46,  78,  50, 198,  80,  78, 204,  86,  74,  81,
          68,  72,  67,  72,  64,  60, 125,  55]))

In [628]:
model.eval()
test_bar = tqdm(test_dataloader, desc = "Testing..")
total_valid_loss = 0.
Actions = []
Cameras = []
with torch.inference_mode():
    for X, lengths in test_bar:
        
            X, lengths = X.to(device), lengths.to(device)
        
            y_hat = model(X,lengths)

            Actions.append(torch.argmax(y_hat[:,:4], dim = 1))
            Cameras.append(torch.argmax(y_hat[:,4:], dim = 1))

Testing..: 100%|██████████| 22/22 [00:02<00:00,  9.61it/s]

In [629]:
Actions = torch.cat(Actions)

In [630]:
Cameras = torch.cat(Cameras)

In [631]:
print(Cameras)

tensor([1, 1, 1,  ..., 1, 1, 1], device='mps:0')

In [632]:
subtask1

[np.int64(124),
 np.int64(78),
 np.int64(207),
 np.int64(66),
 np.int64(83),
 np.int64(65),
 np.int64(86),
 np.int64(100),
 np.int64(87),
 np.int64(90),
 np.int64(161),
 np.int64(86),
 np.int64(71),
 np.int64(200),
 np.int64(78),
 np.int64(139),
 np.int64(58),
 np.int64(51),
 np.int64(91),
 np.int64(139),
 np.int64(75),
 np.int64(71),
 np.int64(88),
 np.int64(66),
 np.int64(115),
 np.int64(79),
 np.int64(66),
 np.int64(68),
 np.int64(81),
 np.int64(67),
 np.int64(181),
 np.int64(71),
 np.int64(95),
 np.int64(67),
 np.int64(158),
 np.int64(71),
 np.int64(132),
 np.int64(81),
 np.int64(110),
 np.int64(65),
 np.int64(79),
 np.int64(138),
 np.int64(87),
 np.int64(74),
 np.int64(107),
 np.int64(59),
 np.int64(46),
 np.int64(78),
 np.int64(50),
 np.int64(198),
 np.int64(80),
 np.int64(78),
 np.int64(102),
 np.int64(86),
 np.int64(74),
 np.int64(81),
 np.int64(68),
 np.int64(72),
 np.int64(67),
 np.int64(72),
 np.int64(64),
 np.int64(60),
 np.int64(125),
 np.int64(55),
 np.int64(83),
 np.int64(115),
 np.int64(76),
 np.int64(84),
 np.int64(111),
 np.int64(152),
 np.int64(239),
 np.int64(86),
 np.int64(87),
 np.int64(82),
 np.int64(64),
 np.int64(69),
 np.int64(93),
 np.int64(62),
 np.int64(71),
 np.int64(95),
 np.int64(172),
 np.int64(91),
 np.int64(67),
 np.int64(200),
 np.int64(71),
 np.int64(107),
 np.int64(59),
 np.int64(80),
 np.int64(58),
 np.int64(98),
 np.int64(141),
 np.int64(116),
 np.int64(175),
 np.int64(80),
 np.int64(67),
 np.int64(69),
 np.int64(85),
 np.int64(73),
 np.int64(88),
 np.int64(98),
 np.int64(80),
 np.int64(88),
 np.int64(114),
 np.int64(141),
 np.int64(76),
 np.int64(50),
 np.int64(62),
 np.int64(61),
 np.int64(64),
 np.int64(131),
 np.int64(53),
 np.int64(97),
 np.int64(63),
 np.int64(207),
 np.int64(80),
 np.int64(68),
 np.int64(62),
 np.int64(96),
 np.int64(151),
 np.int64(54),
 np.int64(81),
 np.int64(62),
 np.int64(61),
 np.int64(72),
 np.int64(68),
 np.int64(173),
 np.int64(84),
 np.int64(227),
 np.int64(108),
 np.int64(54),
 np.int64(62),
 np.int64(74),
 np.int64(63),
 np.int64(158),
 np.int64(81),
 np.int64(70),
 np.int64(71),
 np.int64(62),
 np.int64(99),
 np.int64(80),
 np.int64(90),
 np.int64(53),
 np.int64(58),
 np.int64(60),
 np.int64(65),
 np.int64(56),
 np.int64(65),
 np.int64(79),
 np.int64(63),
 np.int64(81),
 np.int64(138),
 np.int64(164),
 np.int64(166),
 np.int64(48),
 np.int64(54),
 np.int64(230),
 np.int64(66),
 np.int64(72),
 np.int64(70),
 np.int64(52),
 np.int64(92),
 np.int64(74),
 np.int64(136),
 np.int64(60),
 np.int64(60),
 np.int64(71),
 np.int64(288),
 np.int64(87),
 np.int64(68),
 np.int64(71),
 np.int64(65),
 np.int64(92),
 np.int64(56),
 np.int64(108),
 np.int64(74),
 np.int64(116),
 np.int64(104),
 np.int64(91),
 np.int64(78),
 np.int64(70),
 np.int64(62),
 np.int64(83),
 np.int64(99),
 np.int64(82),
 np.int64(78),
 np.int64(67),
 np.int64(90),
 np.int64(76),
 np.int64(203),
 np.int64(66),
 np.int64(58),
 np.int64(207),
 np.int64(56),
 np.int64(78),
 np.int64(61),
 np.int64(197),
 np.int64(93),
 np.int64(66),
 np.int64(115),
 np.int64(79),
 np.int64(90),
 np.int64(87),
 np.int64(78),
 np.int64(72),
 np.int64(97),
 np.int64(70),
 np.int64(67),
 np.int64(107),
 np.int64(59),
 np.int64(201),
 np.int64(118),
 np.int64(85),
 np.int64(54),
 np.int64(106),
 np.int64(67),
 np.int64(84),
 np.int64(144),
 np.int64(121),
 np.int64(50),
 np.int64(86),
 np.int64(136),
 np.int64(86),
 np.int64(79),
 np.int64(80),
 np.int64(60),
 np.int64(135),
 np.int64(199),
 np.int64(84),
 np.int64(56),
 np.int64(74),
 np.int64(100),
 np.int64(122),
 np.int64(81),
 np.int64(93),
 np.int64(128),
 np.int64(126),
 np.int64(80),
 np.int64(88),
 np.int64(160),
 np.int64(141),
 np.int64(129),
 np.int64(77),
 np.int64(75),
 np.int64(83),
 np.int64(66),
 np.int64(67),
 np.int64(53),
 np.int64(183),
 np.int64(79),
 np.int64(66),
 np.int64(87),
 np.int64(90),
 np.int64(300),
 np.int64(80),
 np.int64(168),
 np.int64(183),
 np.int64(70),
 np.int64(139),
 np.int64(239),
 np.int64(80),
 np.int64(63),
 np.int64(59),
 np.int64(79),
 np.int64(66),
 np.int64(85),
 np.int64(75),
 np.int64(69),
 np.int64(87),
 np.int64(135),
 np.int64(66),
 np.int64(77),
 np.int64(58),
 np.int64(59),
 np.int64(87),
 np.int64(198),
 np.int64(91),
 np.int64(200),
 np.int64(89),
 np.int64(153),
 np.int64(86),
 np.int64(65),
 np.int64(66),
 np.int64(155),
 np.int64(70),
 np.int64(196),
 np.int64(84),
 np.int64(181),
 np.int64(47),
 np.int64(152),
 np.int64(117),
 np.int64(79),
 np.int64(183),
 np.int64(81),
 np.int64(62),
 np.int64(87),
 np.int64(47),
 np.int64(95),
 np.int64(57),
 np.int64(74),
 np.int64(58),
 np.int64(70),
 np.int64(59),
 np.int64(207),
 np.int64(75),
 np.int64(64),
 np.int64(83),
 np.int64(65),
 np.int64(56),
 np.int64(70),
 np.int64(86),
 np.int64(85),
 np.int64(72),
 np.int64(90),
 np.int64(63),
 np.int64(61),
 np.int64(88),
 np.int64(79),
 np.int64(92),
 np.int64(93),
 np.int64(112),
 np.int64(70),
 np.int64(71),
 np.int64(228),
 np.int64(71),
 np.int64(87),
 np.int64(66),
 np.int64(85),
 np.int64(76),
 np.int64(92),
 np.int64(67),
 np.int64(69),
 np.int64(161),
 np.int64(154),
 np.int64(64),
 np.int64(72),
 np.int64(65),
 np.int64(105),
 np.int64(176),
 np.int64(81),
 np.int64(90),
 np.int64(93),
 np.int64(64),
 np.int64(228),
 np.int64(83),
 np.int64(80),
 np.int64(85),
 np.int64(67),
 np.int64(79),
 np.int64(125),
 np.int64(70),
 np.int64(145),
 np.int64(68),
 np.int64(87),
 np.int64(77),
 np.int64(72),
 np.int64(127),
 np.int64(60),
 np.int64(91),
 np.int64(81),
 np.int64(60),
 np.int64(77),
 np.int64(87),
 np.int64(238),
 np.int64(72),
 np.int64(78),
 np.int64(67),
 np.int64(84),
 np.int64(79),
 np.int64(77),
 np.int64(111),
 np.int64(83),
 np.int64(60),
 np.int64(135),
 np.int64(162),
 np.int64(75),
 np.int64(84),
 np.int64(64),
 np.int64(68),
 np.int64(67),
 np.int64(132),
 np.int64(82),
 np.int64(88),
 np.int64(51),
 np.int64(57),
 np.int64(138),
 np.int64(90),
 np.int64(100),
 np.int64(112),
 np.int64(73),
 np.int64(77),
 np.int64(101),
 np.int64(126),
 np.int64(78),
 np.int64(161),
 np.int64(90),
 np.int64(77),
 np.int64(75),
 np.int64(107),
 np.int64(62),
 np.int64(87),
 np.int64(163),
 np.int64(71),
 np.int64(61),
 np.int64(72),
 np.int64(183),
 np.int64(128),
 np.int64(190),
 np.int64(57),
 np.int64(66),
 np.int64(57),
 np.int64(112),
 np.int64(228),
 np.int64(78),
 np.int64(94),
 np.int64(98),
 np.int64(151),
 np.int64(173),
 np.int64(92),
 np.int64(79),
 np.int64(96),
 np.int64(73),
 np.int64(67),
 np.int64(57),
 np.int64(66),
 np.int64(77),
 np.int64(67),
 np.int64(67),
 np.int64(63),
 np.int64(77),
 np.int64(48),
 np.int64(54),
 np.int64(60),
 np.int64(59),
 np.int64(63),
 np.int64(190),
 np.int64(266),
 np.int64(103),
 np.int64(86),
 np.int64(90),
 np.int64(224),
 np.int64(157),
 np.int64(56),
 np.int64(65),
 np.int64(134),
 np.int64(169),
 np.int64(97),
 np.int64(85),
 np.int64(167),
 np.int64(61),
 np.int64(67),
 np.int64(86),
 np.int64(66),
 np.int64(60),
 np.int64(133),
 np.int64(81),
 np.int64(66),
 np.int64(105),
 np.int64(89),
 np.int64(83),
 np.int64(80),
 np.int64(73),
 np.int64(86),
 np.int64(71),
 np.int64(94),
 np.int64(162),
 np.int64(73),
 np.int64(63),
 np.int64(153),
 np.int64(145),
 np.int64(92),
 np.int64(96),
 np.int64(62),
 np.int64(58),
 np.int64(55),
 np.int64(76),
 np.int64(158),
 np.int64(81),
 np.int64(79),
 np.int64(86),
 np.int64(63),
 np.int64(71),
 np.int64(219),
 np.int64(70),
 np.int64(69),
 np.int64(131),
 np.int64(152),
 np.int64(58),
 np.int64(74),
 np.int64(66),
 np.int64(164),
 np.int64(87),
 np.int64(64),
 np.int64(85),
 np.int64(55),
 np.int64(70),
 np.int64(59),
 np.int64(72),
 np.int64(83),
 np.int64(75),
 np.int64(95),
 np.int64(67),
 np.int64(65),
 np.int64(71),
 np.int64(81),
 np.int64(67),
 np.int64(86),
 np.int64(76),
 np.int64(121),
 np.int64(65),
 np.int64(53),
 np.int64(85),
 np.int64(94),
 np.int64(176),
 np.int64(59),
 np.int64(54),
 np.int64(138),
 np.int64(112),
 np.int64(165),
 np.int64(60),
 np.int64(84),
 np.int64(189),
 np.int64(56),
 np.int64(85),
 np.int64(90),
 np.int64(107),
 np.int64(79),
 np.int64(84),
 np.int64(82),
 np.int64(73),
 np.int64(182),
 np.int64(86),
 np.int64(85),
 np.int64(67),
 np.int64(191),
 np.int64(61),
 np.int64(81),
 np.int64(82),
 np.int64(68),
 np.int64(52),
 np.int64(64),
 np.int64(154),
 np.int64(86),
 np.int64(68),
 np.int64(54),
 np.int64(82),
 np.int64(66),
 np.int64(70),
 np.int64(160),
 np.int64(81),
 np.int64(65),
 np.int64(70),
 np.int64(63),
 np.int64(59),
 np.int64(182),
 np.int64(78),
 np.int64(60),
 np.int64(75),
 np.int64(80),
 np.int64(67),
 np.int64(78),
 np.int64(86),
 np.int64(134),
 np.int64(71),
 np.int64(71),
 np.int64(208),
 np.int64(85),
 np.int64(208),
 np.int64(72),
 np.int64(103),
 np.int64(90),
 np.int64(76),
 np.int64(101),
 np.int64(94),
 np.int64(91),
 np.int64(152),
 np.int64(70),
 np.int64(122),
 np.int64(106),
 np.int64(59),
 np.int64(115),
 np.int64(63),
 np.int64(71),
 np.int64(110),
 np.int64(230),
 np.int64(83),
 np.int64(160),
 np.int64(69),
 np.int64(78),
 np.int64(84),
 np.int64(138),
 np.int64(64),
 np.int64(69),
 np.int64(85),
 np.int64(73),
 np.int64(125),
 np.int64(69),
 np.int64(79),
 np.int64(63),
 np.int64(69),
 np.int64(82),
 np.int64(54),
 np.int64(103),
 np.int64(198),
 np.int64(83),
 np.int64(74),
 np.int64(176),
 np.int64(60),
 np.int64(63),
 np.int64(77),
 np.int64(67),
 np.int64(203),
 np.int64(70),
 np.int64(81),
 np.int64(182),
 np.int64(86),
 np.int64(81),
 np.int64(157),
 np.int64(71),
 np.int64(83),
 np.int64(60),
 np.int64(60),
 np.int64(90),
 np.int64(127),
 np.int64(65),
 np.int64(199),
 np.int64(71),
 np.int64(75),
 np.int64(81),
 np.int64(50),
 np.int64(71),
 np.int64(108),
 np.int64(75),
 np.int64(98),
 np.int64(91),
 np.int64(62),
 np.int64(140),
 np.int64(75),
 np.int64(81),
 np.int64(52),
 np.int64(87),
 np.int64(67),
 np.int64(58),
 np.int64(80),
 np.int64(53),
 np.int64(48),
 np.int64(58),
 np.int64(75),
 np.int64(84),
 np.int64(224),
 np.int64(60),
 np.int64(66),
 np.int64(66),
 np.int64(94),
 np.int64(220),
 np.int64(82),
 np.int64(58),
 np.int64(190),
 np.int64(59),
 np.int64(71),
 np.int64(133),
 np.int64(245),
 np.int64(61),
 np.int64(56),
 np.int64(139),
 np.int64(62),
 np.int64(72),
 np.int64(76),
 np.int64(54),
 np.int64(80),
 np.int64(112),
 np.int64(60),
 np.int64(81),
 np.int64(67),
 np.int64(219),
 np.int64(68),
 np.int64(66),
 np.int64(49),
 np.int64(60),
 np.int64(72),
 np.int64(78),
 np.int64(72),
 np.int64(57),
 np.int64(70),
 np.int64(190),
 np.int64(83),
 np.int64(68),
 np.int64(74),
 np.int64(50),
 np.int64(99),
 np.int64(102),
 np.int64(50),
 np.int64(171),
 np.int64(58),
 np.int64(162),
 np.int64(73),
 np.int64(93),
 np.int64(140),
 np.int64(80),
 np.int64(103),
 np.int64(64),
 np.int64(61),
 np.int64(198),
 np.int64(168),
 np.int64(81),
 np.int64(93),
 np.int64(161),
 np.int64(161),
 np.int64(63),
 np.int64(79),
 np.int64(112),
 np.int64(79),
 np.int64(78),
 np.int64(68),
 np.int64(80),
 np.int64(83),
 np.int64(80),
 np.int64(88),
 np.int64(73),
 np.int64(288),
 np.int64(80),
 np.int64(76),
 np.int64(208),
 np.int64(81),
 np.int64(77),
 np.int64(80),
 np.int64(69),
 np.int64(53),
 np.int64(69),
 np.int64(125),
 np.int64(121),
 np.int64(166),
 np.int64(73),
 np.int64(60),
 np.int64(131),
 np.int64(165),
 np.int64(92),
 np.int64(92),
 np.int64(152),
 np.int64(156),
 np.int64(70),
 np.int64(57),
 np.int64(81),
 np.int64(82),
 np.int64(58),
 np.int64(217),
 np.int64(71),
 np.int64(82),
 np.int64(77),
 np.int64(86),
 np.int64(139),
 np.int64(106),
 np.int64(62),
 np.int64(81),
 np.int64(64),
 np.int64(83),
 np.int64(78),
 np.int64(84),
 np.int64(77),
 np.int64(88),
 np.int64(61),
 np.int64(109),
 np.int64(71),
 np.int64(83),
 np.int64(68),
 np.int64(61),
 np.int64(80),
 np.int64(60),
 np.int64(63),
 np.int64(63),
 np.int64(58),
 np.int64(79),
 np.int64(114),
 np.int64(58),
 np.int64(69),
 np.int64(53),
 np.int64(77),
 np.int64(274),
 np.int64(87),
 np.int64(59),
 np.int64(69),
 np.int64(99),
 np.int64(58),
 np.int64(68),
 np.int64(74),
 np.int64(139),
 np.int64(90),
 np.int64(60),
 np.int64(54),
 np.int64(74),
 np.int64(50),
 np.int64(60),
 np.int64(92),
 np.int64(82),
 np.int64(88),
 np.int64(79),
 np.int64(111),
 np.int64(90),
 np.int64(81),
 np.int64(78),
 np.int64(76),
 np.int64(88),
 np.int64(53),
 np.int64(138),
 np.int64(81),
 np.int64(84),
 np.int64(89),
 np.int64(77),
 np.int64(116),
 np.int64(91),
 np.int64(152),
 np.int64(74),
 np.int64(77),
 np.int64(88),
 np.int64(90),
 np.int64(83),
 np.int64(63),
 np.int64(62),
 np.int64(86),
 np.int64(52),
 np.int64(72),
 np.int64(51),
 np.int64(81),
 np.int64(50),
 np.int64(70),
 np.int64(72),
 np.int64(71),
 np.int64(67),
 np.int64(75),
 np.int64(79),
 np.int64(56),
 np.int64(58),
 np.int64(83),
 np.int64(71),
 np.int64(94),
 np.int64(72),
 np.int64(109),
 np.int64(71),
 np.int64(84),
 np.int64(71),
 np.int64(108),
 np.int64(75),
 np.int64(67),
 np.int64(138),
 np.int64(61),
 np.int64(57),
 np.int64(139),
 np.int64(118),
 np.int64(85),
 np.int64(139),
 np.int64(53),
 np.int64(159),
 np.int64(92),
 np.int64(68),
 np.int64(121),
 np.int64(74),
 np.int64(56),
 np.int64(72),
 np.int64(87),
 np.int64(188),
 np.int64(82),
 np.int64(121),
 np.int64(74),
 np.int64(76),
 np.int64(68),
 np.int64(267),
 np.int64(87),
 np.int64(274),
 np.int64(95),
 np.int64(65),
 np.int64(79),
 np.int64(169),
 np.int64(84),
 np.int64(85),
 np.int64(92),
 np.int64(60),
 np.int64(111),
 np.int64(104),
 np.int64(90),
 np.int64(73),
 np.int64(225),
 np.int64(89),
 np.int64(85),
 np.int64(182),
 np.int64(216),
 np.int64(69),
 np.int64(144),
 np.int64(58),
 np.int64(155),
 np.int64(92),
 np.int64(159),
 np.int64(79),
 np.int64(52),
 np.int64(49),
 np.int64(105),
 np.int64(60),
 np.int64(71),
 np.int64(103),
 np.int64(140),
 np.int64(70),
 np.int64(94),
 np.int64(223),
 np.int64(58),
 np.int64(57),
 np.int64(88),
 np.int64(87),
 np.int64(57),
 np.int64(158),
 np.int64(92),
 np.int64(83),
 np.int64(69),
 np.int64(55),
 np.int64(159),
 np.int64(88),
 np.int64(138),
 np.int64(64),
 np.int64(240),
 np.int64(68),
 np.int64(106),
 np.int64(57),
 np.int64(76),
 np.int64(63),
 np.int64(80),
 np.int64(52),
 np.int64(63),
 np.int64(84),
 np.int64(145),
 np.int64(60),
 np.int64(59),
 np.int64(207),
 np.int64(86),
 np.int64(88),
 np.int64(160),
 np.int64(108),
 np.int64(86),
 np.int64(62),
 np.int64(66),
 np.int64(88),
 np.int64(300),
 np.int64(86),
 np.int64(66),
 np.int64(90),
 np.int64(67),
 np.int64(133),
 np.int64(223),
 np.int64(57),
 np.int64(88),
 np.int64(68),
 np.int64(62),
 np.int64(51),
 np.int64(71),
 np.int64(74),
 np.int64(60),
 np.int64(65),
 np.int64(62),
 np.int64(60),
 np.int64(81),
 np.int64(62),
 np.int64(76),
 np.int64(61),
 np.int64(78),
 np.int64(57),
 np.int64(71),
 np.int64(134),
 np.int64(75),
 np.int64(80),
 np.int64(66),
 np.int64(53),
 np.int64(60),
 np.int64(78),
 np.int64(71),
 np.int64(155),
 np.int64(96),
 np.int64(76),
 np.int64(92),
 np.int64(68),
 np.int64(115),
 np.int64(103),
 np.int64(68),
 np.int64(95),
 np.int64(66),
 np.int64(60),
 np.int64(78),
 np.int64(95),
 np.int64(65),
 np.int64(223),
 np.int64(140),
 np.int64(81),
 np.int64(77),
 np.int64(140),
 np.int64(104),
 np.int64(138),
 np.int64(88),
 np.int64(165),
 np.int64(87),
 np.int64(46),
 np.int64(66),
 np.int64(60),
 np.int64(83),
 np.int64(69),
 np.int64(71),
 ...]

In [633]:
submission = pd.read_csv("sample_output.csv")

In [634]:
submission

      subtaskID  datapointID  answer
0             1         3361       0
1             2         3361       0
2             3         3361       0
3             1         3362       0
4             2         3362       0
...         ...          ...     ...
4129          2         4737       0
4130          3         4737       0
4131          1         4738       0
4132          2         4738       0
4133          3         4738       0

[4134 rows x 3 columns]

In [635]:
Actions[0].item()

2

In [636]:
answer = []
for i in range(len(Actions)):
    answer.append(subtask1[i])
    answer.append(Actions[i].item())
    answer.append(Cameras[i].item())

In [637]:
submission['answer'] = answer

In [638]:
submission.to_csv("Submission.csv", index = False)